print("<----- Velocity Calculation Program ----->")
print()
distance = int(input("Please insert Distance : "))
time = int(input("Please insert time : "))
print()
print("Velocity =",distance/time, "(km/hr)")
print()
print("<---------------------------------------->")